# Generated by Django 4.2.1 on 2023-05-13 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='Countries',
        ),
        migrations.RenameModel(
            old_name='Language',
            new_name='Languages',
        ),
    ]
