# Generated by Django 4.2.1 on 2023-05-13 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_rename_mame_countries_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Languages',
        ),
    ]
