# Generated by Django 4.2.1 on 2023-05-13 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='countries',
            name='languages',
            field=models.ManyToManyField(to='MainApp.languages'),
        ),
    ]
